# Generated by Django 3.2.15 on 2026-01-28 00:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_jianying_draft_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgressHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(db_index=True, max_length=50, verbose_name='阶段名称')),
                ('message_type', models.CharField(choices=[('token', 'Token消息'), ('stage_update', '阶段更新'), ('progress', '批量进度'), ('done', '完成'), ('error', '错误'), ('connected', '连接成功')], default='stage_update', max_length=20, verbose_name='消息类型')),
                ('progress', models.IntegerField(default=0, help_text='0-100', verbose_name='进度百分比')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='消息内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间戳')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_history', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目进度历史',
                'verbose_name_plural': '项目进度历史',
                'db_table': 'project_progress_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='projectprogresshistory',
            index=models.Index(fields=['project', '-timestamp'], name='project_pro_project_d2b43c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectprogresshistory',
            index=models.Index(fields=['project', 'stage', '-timestamp'], name='project_pro_project_78e7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectprogresshistory',
            index=models.Index(fields=['stage', '-timestamp'], name='project_pro_stage_94aab5_idx'),
        ),
    ]
