# Generated by Django 5.2.10 on 2026-01-31 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_project_progress_history'),
        ('proxy', '0003_proxyusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proxy_config',
            field=models.ForeignKey(blank=True, help_text='项目使用的AI调用代理配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='proxy.proxyconfig', verbose_name='代理配置'),
        ),
    ]
