# Generated by Django 5.2.10 on 2026-02-10 05:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_proxy_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='包含: style, quality, aspect_ratio, llm_provider, image_provider, video_provider 等', verbose_name='参数配置')),
                ('is_system_template', models.BooleanField(default=False, help_text='系统预置模板不可被用户删除', verbose_name='系统预置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '项目模板',
                'verbose_name_plural': '项目模板',
                'db_table': 'project_templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='project_tem_created_d25392_idx'), models.Index(fields=['is_system_template'], name='project_tem_is_syst_afe452_idx')],
            },
        ),
    ]
