# Generated by Django 3.2.15 on 2026-01-28 12:12

import apps.files.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_add_project_progress_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file', models.FileField(max_length=1024, upload_to=apps.files.models.file_upload_path, verbose_name='文件路径')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('document', '文档'), ('audio', '音频'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(editable=False, verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(editable=False, max_length=100, verbose_name='MIME类型')),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='文件哈希(SHA256)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_from', models.CharField(default='web', max_length=50, verbose_name='上传来源')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='projects.project', verbose_name='关联项目')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'uploaded_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_total_size', models.BigIntegerField(default=5368709120, verbose_name='最大总容量')),
                ('max_single_file', models.BigIntegerField(default=104857600, verbose_name='单文件最大')),
                ('max_file_count', models.IntegerField(default=1000, verbose_name='最大文件数量')),
                ('used_total_size', models.BigIntegerField(default=0, editable=False, verbose_name='已用容量')),
                ('used_file_count', models.IntegerField(default=0, editable=False, verbose_name='已用文件数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_quota', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文件配额',
                'verbose_name_plural': '文件配额',
                'db_table': 'file_quotas',
            },
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user', 'file_type'], name='uploaded_fi_user_id_b71b74_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['project', 'file_type'], name='uploaded_fi_project_ee5ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['file_hash'], name='uploaded_fi_file_ha_ea7ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['uploaded_at'], name='uploaded_fi_uploade_ab87d6_idx'),
        ),
    ]
