# Generated by Django 5.2.10 on 2026-01-30 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='代理的唯一标识名称', max_length=200, unique=True, verbose_name='代理名称')),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('socks5', 'SOCKS5')], default='http', help_text='支持的协议: HTTP, HTTPS, SOCKS5', max_length=10, verbose_name='代理协议')),
                ('host', models.CharField(help_text='代理服务器地址（域名或IP）', max_length=255, verbose_name='代理主机')),
                ('port', models.IntegerField(help_text='代理服务器端口（1-65535）', validators=[django.core.validators.MinValueValidator(1, message='端口号必须大于等于1'), django.core.validators.MaxValueValidator(65535, message='端口号必须小于等于65535')], verbose_name='代理端口')),
                ('username', models.CharField(blank=True, help_text='代理认证用户名（可选）', max_length=200, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, help_text='代理认证密码（明文，保存后自动加密并清空）', max_length=255, null=True, verbose_name='密码')),
                ('password_encrypted', models.BinaryField(blank=True, help_text='使用Fernet加密后的密码（二进制存储）', null=True, verbose_name='加密密码')),
                ('is_active', models.BooleanField(default=True, help_text='代理是否可用', verbose_name='是否激活')),
                ('is_healthy', models.BooleanField(default=True, help_text='代理健康状态（由健康检查任务更新）', verbose_name='是否健康')),
                ('priority', models.IntegerField(default=0, help_text='数字越小优先级越高（0为最高优先级）', verbose_name='优先级')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='最后一次使用此代理的时间', null=True, verbose_name='最后使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代理配置',
                'verbose_name_plural': '代理配置',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['is_active', 'is_healthy'], name='proxy_active_healthy_idx'), models.Index(fields=['-last_used_at'], name='proxy_last_used_idx'), models.Index(fields=['protocol'], name='proxy_protocol_idx')],
            },
        ),
    ]
