# Generated by Django 5.2.10 on 2026-01-30 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_provider', models.CharField(help_text="AI客户端类型（如'OpenAIClient', 'ClaudeClient'）", max_length=50, verbose_name='AI提供商')),
                ('endpoint', models.CharField(help_text='调用的API端点路径', max_length=255, verbose_name='API端点')),
                ('response_time_ms', models.PositiveIntegerField(help_text='API响应时间（毫秒）', verbose_name='响应时间')),
                ('success', models.BooleanField(default=True, help_text='调用是否成功', verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, help_text='失败时的错误信息', null=True, verbose_name='错误信息')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='日志记录时间（自动生成）', verbose_name='时间戳')),
                ('proxy', models.ForeignKey(help_text='关联的代理配置', on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='proxy.proxyconfig', verbose_name='代理配置')),
            ],
            options={
                'verbose_name': '代理使用日志',
                'verbose_name_plural': '代理使用日志',
                'db_table': 'proxy_usage_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['proxy', '-timestamp'], name='proxy_time_idx'), models.Index(fields=['ai_provider', 'success', '-timestamp'], name='provider_success_idx')],
            },
        ),
    ]
