# Generated by Django 5.2.10 on 2026-01-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_proxyusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyconfig',
            name='consecutive_failures',
            field=models.IntegerField(default=0, help_text='连续健康检查失败次数（>3次标记为不健康）', verbose_name='连续失败次数'),
        ),
        migrations.AddField(
            model_name='proxyconfig',
            name='consecutive_successes',
            field=models.IntegerField(default=0, help_text='连续健康检查成功次数（3次恢复为健康）', verbose_name='连续成功次数'),
        ),
    ]
