# Generated by Django 5.2.10 on 2026-02-09 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('generation_type', models.CharField(choices=[('portrait', '立绘'), ('voice', '音色'), ('pose_recommendation', '造型推荐')], max_length=50, verbose_name='生成类型')),
                ('prompt_params', models.JSONField(blank=True, default=dict, verbose_name='提示词参数')),
                ('voice_params', models.JSONField(blank=True, default=dict, verbose_name='音色参数')),
                ('result_url', models.URLField(blank=True, verbose_name='结果URL')),
                ('quality_rating', models.IntegerField(blank=True, help_text='1-5星', null=True, verbose_name='质量评分')),
                ('user_feedback', models.TextField(blank=True, verbose_name='用户反馈')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否被采用')),
                ('regeneration_count', models.IntegerField(default=0, verbose_name='重新生成次数')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_history', to='artworks.characterprofile', verbose_name='角色')),
            ],
            options={
                'verbose_name': '生成历史',
                'verbose_name_plural': '生成历史',
                'db_table': 'generation_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('generation_type', models.CharField(choices=[('portrait', '立绘生成'), ('voice', '音色生成'), ('batch', '批量生成'), ('pose_recommendation', '造型推荐')], max_length=50, verbose_name='生成类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('total_items', models.IntegerField(default=0, verbose_name='总项目数')),
                ('completed_items', models.IntegerField(default=0, verbose_name='完成项目数')),
                ('failed_items', models.IntegerField(default=0, verbose_name='失败项目数')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery任务ID')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_progress', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '生成进度',
                'verbose_name_plural': '生成进度',
                'db_table': 'generation_progress',
                'ordering': ['-created_at'],
            },
        ),
    ]
