# Generated by Django 5.2.10 on 2026-02-10 01:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_generationhistory_generationprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='camera_movement_params',
            field=models.JSONField(blank=True, default=dict, help_text='运镜详细参数，JSON格式: {"zoom": "1.5x", "pan": "left", "speed": "medium"}', verbose_name='运镜参数'),
        ),
        migrations.AddField(
            model_name='shot',
            name='character_pose',
            field=models.ForeignKey(blank=True, help_text='镜头中使用的角色造型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='artworks.characterpose', verbose_name='角色造型'),
        ),
        migrations.AddField(
            model_name='shot',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生成时间'),
        ),
        migrations.AddField(
            model_name='shot',
            name='generation_error',
            field=models.TextField(blank=True, verbose_name='生成错误'),
        ),
        migrations.AddField(
            model_name='shot',
            name='generation_retry_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='重试次数'),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_composition',
            field=models.TextField(blank=True, help_text='镜头构图和布局的详细描述', verbose_name='构图描述'),
        ),
    ]
