# Generated by Django 5.2.10 on 2026-02-10 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_shot_camera_movement_params_shot_character_pose_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('change_description', models.TextField(blank=True, help_text='描述本次修改的内容', verbose_name='修改说明')),
                ('content_snapshot', models.JSONField(default=dict, help_text='镜头内容的完整快照', verbose_name='内容快照')),
                ('field_changes', models.JSONField(blank=True, default=dict, help_text='记录变更的字段: {"field": {"old": value, "new": value}}', verbose_name='字段变更')),
                ('is_auto_created', models.BooleanField(default=True, help_text='是否由系统自动创建', verbose_name='自动创建')),
                ('thumbnail', models.ImageField(blank=True, upload_to='shot_versions/thumbnails/', verbose_name='缩略图')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='artworks.shot', verbose_name='所属镜头')),
            ],
            options={
                'verbose_name': '镜头版本',
                'verbose_name_plural': '镜头版本',
                'db_table': 'shot_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['shot', '-version_number'], name='shot_versio_shot_id_5cc1cc_idx'), models.Index(fields=['-created_at'], name='shot_versio_created_7fd23b_idx')],
                'unique_together': {('shot', 'version_number')},
            },
        ),
    ]
