# Generated by Django 5.2.10 on 2026-02-12 02:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0004_shotversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "workflow_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="全局唯一的工作流标识符",
                        unique=True,
                        verbose_name="工作流ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="进度百分比",
                    ),
                ),
                (
                    "total_scenes",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="总场景数",
                    ),
                ),
                (
                    "completed_scenes",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="已完成场景数",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "celery_task_id",
                    models.UUIDField(
                        blank=True,
                        help_text="关联的 Celery 异步任务ID",
                        null=True,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="artworks.chapter",
                        verbose_name="所属章节",
                    ),
                ),
                (
                    "current_scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="当前正在处理的场景",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="artworks.scriptscene",
                        verbose_name="当前场景",
                    ),
                ),
            ],
            options={
                "verbose_name": "章节工作流",
                "verbose_name_plural": "章节工作流",
                "db_table": "chapter_workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("workflow_started", "Workflow Started"),
                            ("workflow_paused", "Workflow Paused"),
                            ("workflow_resumed", "Workflow Resumed"),
                            ("workflow_completed", "Workflow Completed"),
                            ("workflow_failed", "Workflow Failed"),
                            ("workflow_cancelled", "Workflow Cancelled"),
                            ("scene_started", "Scene Started"),
                            ("scene_completed", "Scene Completed"),
                            ("scene_failed", "Scene Failed"),
                            ("scene_skipped", "Scene Skipped"),
                            ("task_retry", "Task Retry"),
                            ("task_timeout", "Task Timeout"),
                        ],
                        max_length=50,
                        verbose_name="事件类型",
                    ),
                ),
                ("message", models.TextField(verbose_name="事件消息")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="事件的额外信息，如场景ID、错误详情等",
                        verbose_name="元数据",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("critical", "严重"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="严重级别",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="artworks.scriptscene",
                        verbose_name="关联场景",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="artworks.chapterworkflow",
                        verbose_name="所属工作流",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流事件",
                "verbose_name_plural": "工作流事件",
                "db_table": "workflow_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chapterworkflow",
            index=models.Index(fields=["workflow_id"], name="chapter_wor_workflo_71a910_idx"),
        ),
        migrations.AddIndex(
            model_name="chapterworkflow",
            index=models.Index(
                fields=["chapter", "-created_at"], name="chapter_wor_chapter_f86553_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chapterworkflow",
            index=models.Index(fields=["status"], name="chapter_wor_status_5dd5fb_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowevent",
            index=models.Index(
                fields=["workflow", "-created_at"], name="workflow_ev_workflo_7e673e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowevent",
            index=models.Index(fields=["event_type"], name="workflow_ev_event_t_e83845_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowevent",
            index=models.Index(fields=["severity"], name="workflow_ev_severit_09954e_idx"),
        ),
    ]
