# Generated by Django 5.2.10 on 2026-02-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0005_chapterworkflow_workflowevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapterworkflow",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="chapterworkflow",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="标记为已删除，实现软删除", verbose_name="已删除"
            ),
        ),
        migrations.AddField(
            model_name="workflowevent",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="workflowevent",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="标记为已删除，实现软删除", verbose_name="已删除"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowevent",
            index=models.Index(fields=["is_deleted"], name="workflow_ev_is_dele_ad304a_idx"),
        ),
    ]
