# Generated by Django 5.2.10 on 2026-02-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0006_chapterworkflow_deleted_at_and_more"),
    ]

    operations = []
