# Generated by Django 5.2.10 on 2026-02-12 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0007_chapter_workflow_status_verbose_name"),
    ]

    operations = []
