# Generated by Django 5.2.10 on 2026-02-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0008_workflow_event_verbose_name"),
        ("artworks", "0011_shot_head_tail_frame_flags"),
    ]

    operations = []
