# Generated by Django 5.2.10 on 2026-02-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artworks", "0012_merge_20260212_1352"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapterworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("running", "运行中"),
                    ("paused", "已暂停"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="scriptscene",
            name="head_frame",
            field=models.ImageField(
                blank=True,
                help_text="场景第一个镜头的预览图，用于转场和快速预览",
                null=True,
                upload_to="scenes/frames/head/%Y/%m/%d/",
                verbose_name="首帧预览",
            ),
        ),
        migrations.AlterField(
            model_name="scriptscene",
            name="tail_frame",
            field=models.ImageField(
                blank=True,
                help_text="场景最后一个镜头的预览图，用于转场和快速预览",
                null=True,
                upload_to="scenes/frames/tail/%Y/%m/%d/",
                verbose_name="尾帧预览",
            ),
        ),
        migrations.AlterField(
            model_name="shot",
            name="is_head_frame",
            field=models.BooleanField(blank=True, default=False, verbose_name="是否首帧"),
        ),
        migrations.AlterField(
            model_name="shot",
            name="is_tail_frame",
            field=models.BooleanField(blank=True, default=False, verbose_name="是否尾帧"),
        ),
        migrations.AlterField(
            model_name="workflowevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("workflow_started", "工作流启动"),
                    ("workflow_paused", "工作流暂停"),
                    ("workflow_resumed", "工作流继续"),
                    ("workflow_completed", "工作流完成"),
                    ("workflow_failed", "工作流失败"),
                    ("workflow_cancelled", "工作流取消"),
                    ("scene_started", "场景开始"),
                    ("scene_completed", "场景完成"),
                    ("scene_failed", "场景失败"),
                    ("scene_skipped", "场景跳过"),
                    ("task_retry", "Task Retry"),
                    ("task_timeout", "Task Timeout"),
                ],
                max_length=50,
                verbose_name="事件类型",
            ),
        ),
    ]
