# Generated by Django 5.2.10 on 2026-01-30 06:20

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('view', '查看')], db_index=True, max_length=20, verbose_name='操作类型')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='模型名称')),
                ('object_id', models.CharField(db_index=True, max_length=100, verbose_name='对象ID')),
                ('object_repr', models.CharField(max_length=200, verbose_name='对象表示')),
                ('change_message', models.TextField(blank=True, verbose_name='变更消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'user'], name='users_audit_created_83d253_idx'), models.Index(fields=['model_name', 'object_id'], name='users_audit_model_n_fb8a47_idx'), models.Index(fields=['action', '-created_at'], name='users_audit_action_c40010_idx')],
            },
        ),
    ]
