# Generated by Django 5.2.10 on 2026-01-30 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_create_mock_providers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelprovider',
            options={'ordering': ['-is_system_default', '-priority', '-created_at'], 'verbose_name': '模型提供商', 'verbose_name_plural': '模型提供商'},
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_models', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='modelprovider',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='系统级默认资源：所有用户可见且不可编辑（除创建者）', verbose_name='系统级默认资源'),
        ),
        migrations.AddIndex(
            model_name='modelprovider',
            index=models.Index(fields=['-is_system_default', 'created_by'], name='model_provi_is_syst_91ba50_idx'),
        ),
    ]
