# Generated by Django 5.2.10 on 2026-01-31 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0005_alter_modelprovider_options_modelprovider_created_by_and_more"),
        ("proxy", "0004_proxyconfig_consecutive_failures_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="modelprovider",
            name="proxy_config",
            field=models.ForeignKey(
                blank=True,
                help_text="选择用于此模型API请求的代理（可选）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="model_providers",
                to="proxy.proxyconfig",
                verbose_name="代理配置",
            ),
        ),
        migrations.AddField(
            model_name="modelprovider",
            name="use_proxy",
            field=models.BooleanField(
                default=False, help_text="是否启用代理进行API请求", verbose_name="启用代理"
            ),
        ),
        migrations.AddIndex(
            model_name="modelprovider",
            index=models.Index(
                fields=["use_proxy", "proxy_config"], name="model_provi_use_pro_f82839_idx"
            ),
        ),
    ]
