# Generated by Django 5.2.10 on 2026-02-10 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[('llm', 'LLM文本生成'), ('image', '图像生成'), ('tts', '语音合成')], help_text='引擎类型 (每种类型只能有一个配置)', max_length=10, unique=True, verbose_name='引擎类型')),
                ('name', models.CharField(help_text='引擎配置的显示名称', max_length=255, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, help_text='引擎配置的详细说明', verbose_name='描述')),
                ('primary_provider', models.CharField(help_text='主引擎提供商 (如: ollama, openai)', max_length=50, verbose_name='主引擎提供商')),
                ('primary_config', models.JSONField(default=dict, help_text='主引擎配置参数 (JSON格式)\nLLM示例: {"base_url": "http://localhost:11434", "model": "llama2:7b", "temperature": 0.7}\nImage示例: {"base_url": "http://localhost:8188", "workflow": "..."}\nTTS示例: {"voice": "zh-CN-XiaoxiaoNeural", "rate": "+0%"}', verbose_name='主引擎配置')),
                ('fallback_provider', models.CharField(blank=True, help_text='备份引擎提供商 (可选)', max_length=50, verbose_name='备份引擎提供商')),
                ('fallback_config', models.JSONField(blank=True, default=dict, help_text='备份引擎配置参数 (JSON格式)', verbose_name='备份引擎配置')),
                ('fallback_threshold', models.IntegerField(default=3, help_text='连续失败多少次后切换到备份引擎', verbose_name='失败阈值')),
                ('fallback_timeout', models.IntegerField(default=30, help_text='请求超时时间 (秒)', verbose_name='超时时间(秒)')),
                ('auto_fallback', models.BooleanField(default=True, help_text='是否自动启用Fallback切换', verbose_name='自动Fallback')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('current_provider', models.CharField(blank=True, help_text='当前使用的引擎提供商', max_length=50, verbose_name='当前引擎')),
                ('health_status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '异常'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='健康状态')),
                ('last_health_check', models.DateTimeField(auto_now=True, verbose_name='最后检查时间')),
                ('total_requests', models.IntegerField(default=0, verbose_name='总请求数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('failure_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='平均响应时间(ms)')),
                ('total_cost', models.FloatField(default=0.0, help_text='实际花费的金额 (美元)', verbose_name='实际花费($)')),
                ('saved_cost', models.FloatField(default=0.0, help_text='使用本地引擎节省的金额 (美元)', verbose_name='节省金额($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '引擎配置',
                'verbose_name_plural': '引擎配置',
                'ordering': ['engine_type'],
            },
        ),
        migrations.CreateModel(
            name='FallbackEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_provider', models.CharField(max_length=50, verbose_name='源引擎')),
                ('to_provider', models.CharField(max_length=50, verbose_name='目标引擎')),
                ('reason', models.CharField(choices=[('timeout', '超时'), ('failure', '连续失败'), ('manual', '手动切换'), ('error', '引擎异常')], max_length=20, verbose_name='切换原因')),
                ('reason_detail', models.TextField(blank=True, verbose_name='原因详情')),
                ('affected_requests', models.IntegerField(default=0, verbose_name='影响的请求数')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_logs', to='engines.engineconfig', verbose_name='引擎配置')),
            ],
            options={
                'verbose_name': 'Fallback事件日志',
                'verbose_name_plural': 'Fallback事件日志',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '异常')], max_length=20, verbose_name='状态')),
                ('response_time', models.FloatField(blank=True, help_text='响应时间 (毫秒)', null=True, verbose_name='响应时间(ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='错误代码')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='engines.engineconfig', verbose_name='引擎配置')),
            ],
            options={
                'verbose_name': '引擎健康日志',
                'verbose_name_plural': '引擎健康日志',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['engine', '-checked_at'], name='engines_eng_engine__f560fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='EngineUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='实际使用的提供商')),
                ('request_type', models.CharField(max_length=20, verbose_name='请求类型')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('response_time', models.FloatField(verbose_name='响应时间(ms)')),
                ('token_count', models.IntegerField(blank=True, null=True, verbose_name='Token数量')),
                ('cost', models.FloatField(default=0.0, verbose_name='实际花费($)')),
                ('saved_cost', models.FloatField(default=0.0, verbose_name='节省金额($)')),
                ('project_id', models.UUIDField(blank=True, null=True, verbose_name='项目ID')),
                ('shot_id', models.UUIDField(blank=True, null=True, verbose_name='镜头ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='engines.engineconfig', verbose_name='引擎配置')),
            ],
            options={
                'verbose_name': '引擎使用日志',
                'verbose_name_plural': '引擎使用日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['engine', '-created_at'], name='engines_eng_engine__d2bf58_idx'), models.Index(fields=['success', '-created_at'], name='engines_eng_success_0bd518_idx')],
            },
        ),
    ]
