# Generated by Django 5.2.10 on 2026-01-30 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_create_mock_prompt_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompttemplateset',
            options={'ordering': ['-is_system_default', '-created_at'], 'verbose_name': '提示词集', 'verbose_name_plural': '提示词集'},
        ),
        migrations.AddField(
            model_name='prompttemplateset',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='系统级默认资源：所有用户可见且不可编辑（除创建者）', verbose_name='系统级默认资源'),
        ),
        migrations.AlterField(
            model_name='prompttemplateset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prompt_sets', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddIndex(
            model_name='prompttemplateset',
            index=models.Index(fields=['-is_system_default', 'created_by'], name='prompt_temp_is_syst_41f816_idx'),
        ),
    ]
